name: Node CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - name: Install dependencies
      run: |
        npm ci
        # npm is an awful piece of software
        # https://github.com/npm/cli/issues/4828
        npm install --include=optional sharp
    - name: Run tests
      run: npm test
